version: '3.10'
services:

  backend:
    container_name: BACKEND
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    command: >
      sh -c "alembic upgrade head
      && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: POSTGRES
    image: postgres:14.0-alpine
    restart: on-failure
    ports:
      - '5432'
    env_file:
      .env
    environment:
      POSTGRES_NAME: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
